# Generated by Django 4.0.4 on 2022-06-08 17:12

import user.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0004_alter_account_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=user.models.EmailLowerField(max_length=60, unique=True, verbose_name='email'),
        ),
    ]
