# Generated by Django 4.0.4 on 2022-06-09 21:41

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_account_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(upload_to='avatars'),
        ),
    ]
