# Generated by Django 4.0.4 on 2022-06-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_account_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default='default.png', max_length=255, null=True, upload_to='profile_images/profile_image.png'),
        ),
    ]
