# Generated by Django 4.0.4 on 2022-06-09 22:00

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_account_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='default.jpg', null=True, upload_to='profile_images'),
        ),
    ]
