# Generated by Django 4.0.4 on 2022-06-04 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_avatar_delete_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avatar',
            new_name='Profile',
        ),
    ]
