# Generated by Django 4.0.4 on 2022-06-04 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_rename_avatar_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Avatar',
        ),
    ]
