# Generated by Django 4.0.4 on 2022-05-18 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('portions', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1)])),
                ('ingredients', models.CharField(max_length=300)),
                ('steps', models.CharField(max_length=300)),
                ('filters', models.CharField(max_length=300)),
            ],
        ),
    ]
