# Generated by Django 4.0.4 on 2022-06-04 13:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(default='', max_length=200)),
                ('portions', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1)])),
                ('ingredients', models.CharField(max_length=300)),
                ('steps', models.TextField()),
                ('filters', models.CharField(max_length=300)),
                ('user', models.ManyToManyField(blank=True, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
