# Generated by Django 4.0.4 on 2022-06-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='recipe_default.png', upload_to='recipe_images'),
        ),
    ]
