# Generated by Django 4.0.4 on 2022-06-06 15:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
