# Generated by Django 4.0.4 on 2022-05-26 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0004_recipeinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeinstance',
            name='recipe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='recipes.recipe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipeinstance',
            name='recipe_user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
