# Generated by Django 4.0.4 on 2022-05-27 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0005_alter_recipeinstance_recipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ManyToManyField(related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
