# Generated by Django 4.0.4 on 2022-05-31 22:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
