# Generated by Django 4.0.4 on 2022-05-27 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0006_recipe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
