# Generated by Django 4.0.4 on 2022-06-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=30)),
                ('contains', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_ingredients',
            field=models.ManyToManyField(related_name='ingredient', to='recipes.ingredient'),
        ),
    ]
