# Generated by Django 4.0.4 on 2022-06-27 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_ingredient_remove_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ingredient'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Recipe'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Recipe_ingredient'},
        ),
    ]
