# Generated by Django 4.0.7 on 2023-03-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_recipeingredient_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='calories',
            field=models.IntegerField(null=True),
        ),
    ]
