# Generated by Django 4.0.7 on 2023-03-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_recipeingredient_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='total_calories',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
